#include <iostream>

#define BOGDAN (
#define STUMBIN )
#define OLEG {
#define SUBAEV }
#define KIRILL int
#define OVCHINNIKOV main
#define JAFAR [
#define AMANULLAKH ]
#define SASHA ;
#define POPOV <<
#define FATTAKHOV cout
#define BABAEVA ::
#define ULKER std
#define SHAMIL endl
#define GADZHIEV cin
#define MORGENSHTERN >>
#define ELDZHEY rows
#define CADILLAC *
#define MERIN arr
#define KEK new
#define LOL =
#define TROLLFACE delete
#define ARTEM "Enter cols"
#define MASLOW "Enter rows"
#define PLOKHOW for
#define BESLYAGA <
#define TOKACHEW rand() % 100
#define GRIHAN i
#define MYFRIENDS 0
#define BUSINESSMAN j
#define WONDERBOSH ++
#define YEET "\t"
#define N728 cols

KIRILL OVCHINNIKOV BOGDAN STUMBIN
OLEG
    KIRILL ELDZHEY SASHA
    KIRILL N728 SASHA
    ULKER BABAEVA FATTAKHOV POPOV MASLOW POPOV ULKER BABAEVA SHAMIL SASHA
    ULKER BABAEVA GADZHIEV MORGENSHTERN ELDZHEY SASHA
    ULKER BABAEVA FATTAKHOV POPOV ARTEM POPOV ULKER BABAEVA SHAMIL SASHA
    ULKER BABAEVA GADZHIEV MORGENSHTERN N728 SASHA
    ULKER BABAEVA FATTAKHOV POPOV ULKER BABAEVA SHAMIL SASHA
    KIRILL CADILLAC CADILLAC MERIN LOL KEK KIRILL CADILLAC JAFAR ELDZHEY AMANULLAKH SASHA

    PLOKHOW BOGDAN KIRILL GRIHAN LOL MYFRIENDS SASHA GRIHAN BESLYAGA ELDZHEY SASHA GRIHAN WONDERBOSH STUMBIN
        MERIN JAFAR GRIHAN AMANULLAKH LOL KEK KIRILL JAFAR N728 AMANULLAKH SASHA

    PLOKHOW BOGDAN KIRILL GRIHAN LOL MYFRIENDS SASHA GRIHAN BESLYAGA ELDZHEY SASHA GRIHAN WONDERBOSH STUMBIN
    OLEG
        PLOKHOW BOGDAN KIRILL BUSINESSMAN LOL MYFRIENDS SASHA BUSINESSMAN BESLYAGA N728 SASHA BUSINESSMAN WONDERBOSH STUMBIN
        OLEG
            MERIN JAFAR GRIHAN AMANULLAKH JAFAR BUSINESSMAN AMANULLAKH LOL TOKACHEW SASHA
            ULKER BABAEVA FATTAKHOV POPOV MERIN JAFAR GRIHAN AMANULLAKH JAFAR BUSINESSMAN AMANULLAKH POPOV YEET SASHA
        SUBAEV
        ULKER BABAEVA FATTAKHOV POPOV ULKER BABAEVA SHAMIL SASHA
    SUBAEV

    PLOKHOW BOGDAN KIRILL GRIHAN LOL MYFRIENDS SASHA GRIHAN BESLYAGA ELDZHEY SASHA GRIHAN WONDERBOSH STUMBIN
    OLEG
        TROLLFACE JAFAR AMANULLAKH MERIN JAFAR GRIHAN AMANULLAKH SASHA
    SUBAEV
    TROLLFACE JAFAR AMANULLAKH MERIN SASHA
    
SUBAEV
